"""add spotify fields to song

Revision ID: 4f2fc995bf83
Revises: 26fb804d7aa2
Create Date: 2026-05-27 11:03:42.995836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2fc995bf83'
down_revision = '26fb804d7aa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('spotify_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_column('spotify_url')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
