"""Add filter fields

Revision ID: fcaa184bd941
Revises: 
Create Date: 2025-06-05 22:45:34.488150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcaa184bd941'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tempo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('singer_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('holiday', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_column('holiday')
        batch_op.drop_column('singer_type')
        batch_op.drop_column('tempo')

    # ### end Alembic commands ###
